export default [
  {
    bankIcon: '/images/payment/product-img-empty.svg',
    bankId: null,
    bankImage: '/images/payment/product-img-empty.svg',
    bankName: null,
    expiryDate: '12/33',
    expiryMonth: 12,
    expiryYear: 2033,
    id: '590925219668099073',
    isDefault: true,
    isExpired: false,
    maskedNumber: '411111XXXXXX1111',
    maskedNumberByStar: '**** **** **** 1111',
    type: 'Visa',
    typeIcon: '/icons/types-credit-card/visa-no-border.svg',
  },
  {
    bankIcon: '/images/payment/product-img-empty.svg',
    bankId: '10',
    bankImage: '/images/payment/product-img-empty.svg',
    bankName: 'KCC',
    expiryDate: '12/33',
    expiryMonth: 12,
    expiryYear: 2033,
    id: '604578118707118081',
    isDefault: false,
    isExpired: false,
    maskedNumber: '512345XXXXXX2346',
    maskedNumberByStar: '**** **** **** 2346',
    type: 'MasterCard',
    typeIcon: '/icons/types-credit-card/master-no-border.svg',
  },
];
