export const WISHLIST_FETCH_STARTED = 'WISHLIST_FETCH_STARTED'
export const WISHLIST_FETCHED = 'WISHLIST_FETCHED'

export const ADD_TO_WISHLIST_STARTED = 'ADD_TO_WISHLIST_STARTED'
export const REMOVE_FROM_WISHLIST_STARTED = 'REMOVE_FROM_WISHLIST_STARTED'
export const REMOVE_FROM_WISHLIST_FINISHED = 'REMOVE_FROM_WISHLIST_FINISHED'
export const REMOVE_FROM_WISHLIST_FAILED = 'REMOVE_FROM_WISHLIST_FAILED'
export const WISHLIST_FETCH_PRODUCTS_STARTED = 'WISHLIST_FETCH_PRODUCTS_STARTED'
export const WISHLIST_PRODUCTS_FETCHED = 'WISHLIST_PRODUCTS_FETCHED'
