export const slotMore7 = [
  {
    id: 0,
    intervalStart: '2020-10-31',
    intervalEnd: '2020-11-06',
    days: [
      {
        date: '2020-10-31',
        slots: [
          {
            id: 203,
            timeFrom: '10:00',
            timeTo: '12:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 204,
            timeFrom: '12:00',
            timeTo: '14:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 205,
            timeFrom: '14:00',
            timeTo: '16:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 206,
            timeFrom: '16:00',
            timeTo: '18:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 207,
            timeFrom: '18:00',
            timeTo: '20:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 208,
            timeFrom: '20:00',
            timeTo: '22:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
        ],
      },
      {
        date: '2020-11-01',
        slots: [
          {
            id: 203,
            timeFrom: '10:00',
            timeTo: '12:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 204,
            timeFrom: '12:00',
            timeTo: '14:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 205,
            timeFrom: '14:00',
            timeTo: '16:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 206,
            timeFrom: '16:00',
            timeTo: '18:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 207,
            timeFrom: '18:00',
            timeTo: '20:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 208,
            timeFrom: '20:00',
            timeTo: '22:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
        ],
      },
      {
        date: '2020-11-02',
        slots: [
          {
            id: 203,
            timeFrom: '10:00',
            timeTo: '12:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 204,
            timeFrom: '12:00',
            timeTo: '14:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 205,
            timeFrom: '14:00',
            timeTo: '16:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 206,
            timeFrom: '16:00',
            timeTo: '18:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 207,
            timeFrom: '18:00',
            timeTo: '20:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 208,
            timeFrom: '20:00',
            timeTo: '22:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
        ],
      },
      {
        date: '2020-11-03',
        slots: [
          {
            id: 203,
            timeFrom: '10:00',
            timeTo: '12:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 204,
            timeFrom: '12:00',
            timeTo: '14:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 205,
            timeFrom: '14:00',
            timeTo: '16:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 206,
            timeFrom: '16:00',
            timeTo: '18:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 207,
            timeFrom: '18:00',
            timeTo: '20:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 208,
            timeFrom: '20:00',
            timeTo: '22:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
        ],
      },
      {
        date: '2020-11-04',
        slots: [
          {
            id: 203,
            timeFrom: '10:00',
            timeTo: '12:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 204,
            timeFrom: '12:00',
            timeTo: '14:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 205,
            timeFrom: '14:00',
            timeTo: '16:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 206,
            timeFrom: '16:00',
            timeTo: '18:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 207,
            timeFrom: '18:00',
            timeTo: '20:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 208,
            timeFrom: '20:00',
            timeTo: '22:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
        ],
      },
      {
        date: '2020-11-05',
        slots: [
          {
            id: 203,
            timeFrom: '10:00',
            timeTo: '12:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 204,
            timeFrom: '12:00',
            timeTo: '14:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 205,
            timeFrom: '14:00',
            timeTo: '16:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 206,
            timeFrom: '16:00',
            timeTo: '18:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 207,
            timeFrom: '18:00',
            timeTo: '20:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 208,
            timeFrom: '20:00',
            timeTo: '22:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
        ],
      },
      {
        date: '2020-11-06',
        slots: [
          {
            id: 203,
            timeFrom: '10:00',
            timeTo: '12:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 204,
            timeFrom: '12:00',
            timeTo: '14:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 205,
            timeFrom: '14:00',
            timeTo: '16:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 206,
            timeFrom: '16:00',
            timeTo: '18:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 207,
            timeFrom: '18:00',
            timeTo: '20:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 208,
            timeFrom: '20:00',
            timeTo: '22:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
        ],
      },
    ],
  },
  {
    id: 1,
    intervalStart: '2020-11-07',
    intervalEnd: '2020-11-13',
    days: [
      {
        date: '2020-11-07',
        slots: [
          {
            id: 203,
            timeFrom: '10:00',
            timeTo: '12:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 204,
            timeFrom: '12:00',
            timeTo: '14:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 205,
            timeFrom: '14:00',
            timeTo: '16:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 206,
            timeFrom: '16:00',
            timeTo: '18:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 207,
            timeFrom: '18:00',
            timeTo: '20:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 208,
            timeFrom: '20:00',
            timeTo: '22:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
        ],
      },
      {
        date: '2020-11-08',
        slots: [
          {
            id: 203,
            timeFrom: '10:00',
            timeTo: '12:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 204,
            timeFrom: '12:00',
            timeTo: '14:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 205,
            timeFrom: '14:00',
            timeTo: '16:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 206,
            timeFrom: '16:00',
            timeTo: '18:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 207,
            timeFrom: '18:00',
            timeTo: '20:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 208,
            timeFrom: '20:00',
            timeTo: '22:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
        ],
      },
      {
        date: '2020-11-09',
        slots: [
          {
            id: 203,
            timeFrom: '10:00',
            timeTo: '12:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 204,
            timeFrom: '12:00',
            timeTo: '14:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 205,
            timeFrom: '14:00',
            timeTo: '16:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 206,
            timeFrom: '16:00',
            timeTo: '18:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 207,
            timeFrom: '18:00',
            timeTo: '20:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 208,
            timeFrom: '20:00',
            timeTo: '22:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
        ],
      },
      {
        date: '2020-11-10',
        slots: [
          {
            id: 203,
            timeFrom: '10:00',
            timeTo: '12:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 204,
            timeFrom: '12:00',
            timeTo: '14:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 205,
            timeFrom: '14:00',
            timeTo: '16:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 206,
            timeFrom: '16:00',
            timeTo: '18:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 207,
            timeFrom: '18:00',
            timeTo: '20:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 208,
            timeFrom: '20:00',
            timeTo: '22:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
        ],
      },
      {
        date: '2020-11-11',
        slots: [
          {
            id: 203,
            timeFrom: '10:00',
            timeTo: '12:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 204,
            timeFrom: '12:00',
            timeTo: '14:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 205,
            timeFrom: '14:00',
            timeTo: '16:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 206,
            timeFrom: '16:00',
            timeTo: '18:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 207,
            timeFrom: '18:00',
            timeTo: '20:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 208,
            timeFrom: '20:00',
            timeTo: '22:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
        ],
      },
      {
        date: '2020-11-12',
        slots: [
          {
            id: 203,
            timeFrom: '10:00',
            timeTo: '12:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 204,
            timeFrom: '12:00',
            timeTo: '14:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 205,
            timeFrom: '14:00',
            timeTo: '16:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 206,
            timeFrom: '16:00',
            timeTo: '18:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 207,
            timeFrom: '18:00',
            timeTo: '20:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 208,
            timeFrom: '20:00',
            timeTo: '22:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
        ],
      },
      {
        date: '2020-11-13',
        slots: [
          {
            id: 203,
            timeFrom: '10:00',
            timeTo: '12:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 204,
            timeFrom: '12:00',
            timeTo: '14:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 205,
            timeFrom: '14:00',
            timeTo: '16:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 206,
            timeFrom: '16:00',
            timeTo: '18:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 207,
            timeFrom: '18:00',
            timeTo: '20:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 208,
            timeFrom: '20:00',
            timeTo: '22:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
        ],
      },
    ],
  },
];

export const slot = [
  {
    id: 0,
    intervalStart: '2020-10-31',
    intervalEnd: '2020-11-06',
    days: [
      {
        date: '2020-10-31',
        slots: [
          {
            id: 203,
            timeFrom: '10:00',
            timeTo: '12:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 204,
            timeFrom: '12:00',
            timeTo: '14:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 205,
            timeFrom: '14:00',
            timeTo: '16:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 206,
            timeFrom: '16:00',
            timeTo: '18:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 207,
            timeFrom: '18:00',
            timeTo: '20:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 208,
            timeFrom: '20:00',
            timeTo: '22:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
        ],
      },
      {
        date: '2020-11-01',
        slots: [
          {
            id: 203,
            timeFrom: '10:00',
            timeTo: '12:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 204,
            timeFrom: '12:00',
            timeTo: '14:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 205,
            timeFrom: '14:00',
            timeTo: '16:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 206,
            timeFrom: '16:00',
            timeTo: '18:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 207,
            timeFrom: '18:00',
            timeTo: '20:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 208,
            timeFrom: '20:00',
            timeTo: '22:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
        ],
      },
      {
        date: '2020-11-02',
        slots: [
          {
            id: 203,
            timeFrom: '10:00',
            timeTo: '12:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 204,
            timeFrom: '12:00',
            timeTo: '14:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 205,
            timeFrom: '14:00',
            timeTo: '16:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 206,
            timeFrom: '16:00',
            timeTo: '18:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 207,
            timeFrom: '18:00',
            timeTo: '20:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 208,
            timeFrom: '20:00',
            timeTo: '22:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
        ],
      },
      {
        date: '2020-11-03',
        slots: [
          {
            id: 203,
            timeFrom: '10:00',
            timeTo: '12:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 204,
            timeFrom: '12:00',
            timeTo: '14:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 205,
            timeFrom: '14:00',
            timeTo: '16:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 206,
            timeFrom: '16:00',
            timeTo: '18:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 207,
            timeFrom: '18:00',
            timeTo: '20:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 208,
            timeFrom: '20:00',
            timeTo: '22:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
        ],
      },
      {
        date: '2020-11-04',
        slots: [
          {
            id: 203,
            timeFrom: '10:00',
            timeTo: '12:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 204,
            timeFrom: '12:00',
            timeTo: '14:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 205,
            timeFrom: '14:00',
            timeTo: '16:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 206,
            timeFrom: '16:00',
            timeTo: '18:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 207,
            timeFrom: '18:00',
            timeTo: '20:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 208,
            timeFrom: '20:00',
            timeTo: '22:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
        ],
      },
      {
        date: '2020-11-05',
        slots: [
          {
            id: 203,
            timeFrom: '10:00',
            timeTo: '12:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 204,
            timeFrom: '12:00',
            timeTo: '14:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 205,
            timeFrom: '14:00',
            timeTo: '16:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 206,
            timeFrom: '16:00',
            timeTo: '18:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 207,
            timeFrom: '18:00',
            timeTo: '20:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 208,
            timeFrom: '20:00',
            timeTo: '22:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
        ],
      },
      {
        date: '2020-11-06',
        slots: [
          {
            id: 203,
            timeFrom: '10:00',
            timeTo: '12:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 204,
            timeFrom: '12:00',
            timeTo: '14:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 205,
            timeFrom: '14:00',
            timeTo: '16:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 206,
            timeFrom: '16:00',
            timeTo: '18:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 207,
            timeFrom: '18:00',
            timeTo: '20:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
          {
            id: 208,
            timeFrom: '20:00',
            timeTo: '22:00',
            cost: 60,
            quota: 200,
            available: 200,
            enabled: true,
            isAllow: true,
          },
        ],
      },
    ],
  },
];
