const types = {
  SET_PAYMENT: 'SET_PAYMENT',
  SET_PAYMENT_LOADING: 'SET_PAYMENT_LOADING',
  SET_PAYMENT_CODE: 'SET_PAYMENT_CODE',
  SET_PAYMENT_SERVICE_FULL_PAYMENT: 'SET_PAYMENT_SERVICE_FULL_PAYMENT',
  SET_PAYMENT_SERVICE_FULL_PAYMENT_SAVE_CARD:
    'SET_PAYMENT_SERVICE_FULL_PAYMENT_SAVE_CARD',
  SET_PAYMENT_SERVICE_FULL_PAYMENT_SAVED_CARD:
    'SET_PAYMENT_SERVICE_FULL_PAYMENT_SAVED_CARD',
  SET_PAYMENT_SERVICE_FULL_PAYMENT_IS_INVALID_CARD:
    'SET_PAYMENT_SERVICE_FULL_PAYMENT_IS_INVALID_CARD',
  SET_PAYMENT_T1C_INFO: 'SET_PAYMENT_T1C_INFO',
  SET_PATMENT_REMARK: 'SET_PATMENT_REMARK',
  SET_PAYMENT_SUBSTITUTION: 'SET_PAYMENT_SUBSTITUTION',
  SET_PAYMENT_IS_REQUEST_TAX: 'SET_PAYMENT_IS_REQUEST_TAX',
  SET_PAYMENT_CARD_PROMOTION: 'SET_PAYMENT_CARD_PROMOTION',
};

const typeUpdatePayment = {
  SET_PAYMENT_METHOD: 'SET_PAYMENT_METHOD',
  SET_PROMOTION_CODE: 'SET_PROMOTION_CODE',
};

const typesPaymentMethods = {
  PAYMENT_SERVICE_FULLPAYMENT: 'payment_service_fullpayment',
  CASHONDELIVERY: 'cashondelivery',
  CREDITCARDONDELIVERY: 'creditcardondelivery',
  CREDITTERM: 'credit_term',
  PAYATSTORE: 'payatstore',
  FREE: 'free',
};

export { types, typeUpdatePayment, typesPaymentMethods };
