import { find } from 'lodash';
// import { config, baseUrl } from '../config'

const mockStores = [
  {
    store_code: 'rama_2_en',
    store_name: 'Rama 2',
    zip_code: '10150',
    lang: 'en',
  },
  {
    store_code: 'rama_2_th',
    store_name: 'Rama 2',
    zip_code: '10150',
    lang: 'th',
  },
  {
    store_code: 'rama_9_en',
    store_name: 'Rama 9',
    zip_code: '10310',
    lang: 'en',
  },
  {
    store_code: 'rama_9_th',
    store_name: 'Rama 9',
    zip_code: '10310',
    lang: 'th',
  },
  {
    store_code: 'central_plaza_pinklao_en',
    store_name: 'Central Plaza Pinklao',
    zip_code: '10700',
    lang: 'en',
  },
  {
    store_code: 'central_plaza_pinklao_th',
    store_name: 'Central Plaza Pinklao',
    zip_code: '10700',
    lang: 'th',
  },
  {
    store_code: 'central_plaza_rama_3_en',
    store_name: 'Central Plaza Rama 3',
    zip_code: '10120',
    lang: 'en',
  },
  {
    store_code: 'central_plaza_rama_3_th',
    store_name: 'Central Plaza Rama 3',
    zip_code: '10120',
    lang: 'th',
  },
  {
    store_code: 'central_plaza_ramintra_en',
    store_name: 'Central Plaza Ramintra',
    zip_code: '10220',
    lang: 'en',
  },
  {
    store_code: 'central_plaza_ramintra_th',
    store_name: 'Central Plaza Ramintra',
    zip_code: '10220',
    lang: 'th',
  },
  {
    store_code: 'robinson_fashion_island_en',
    store_name: 'Robinson Fashion Island',
    zip_code: '10230',
    lang: 'en',
  },
  {
    store_code: 'robinson_fashion_island_th',
    store_name: 'Robinson Fashion Island',
    zip_code: '10230',
    lang: 'th',
  },
  {
    store_code: 'robinson_future_park_rangist_en',
    store_name: 'Robinson Future Park Rangsit',
    zip_code: '12130',
    lang: 'en',
  },
  {
    store_code: 'robinson_future_park_rangist_th',
    store_name: 'Robinson Future Park Rangsit',
    zip_code: '12130',
    lang: 'th',
  },
  {
    store_code: 'robinson_sukhumvit_19_en',
    store_name: 'Robinson Sukhumvit 19',
    zip_code: '10110',
    lang: 'en',
  },
  {
    store_code: 'robinson_sukhumvit_19_th',
    store_name: 'Robinson Sukhumvit 19',
    zip_code: '10110',
    lang: 'th',
  },
  {
    store_code: 'robinson_bangrak_en',
    store_name: 'Robinson Bangrak 19',
    zip_code: '10500',
    lang: 'en',
  },
  {
    store_code: 'robinson_bangrak_th',
    store_name: 'Robinson Bangrak 19',
    zip_code: '10500',
    lang: 'th',
  },
  {
    store_code: 'seacon_bangkae_en',
    store_name: 'Seacon Bangkae',
    zip_code: '10160',
    lang: 'en',
  },
  {
    store_code: 'seacon_bangkae_th',
    store_name: 'Seacon Bangkae',
    zip_code: '10160',
    lang: 'th',
  },
  {
    store_code: 'robinson_srinakarin_en',
    store_name: 'Robinson Srinakarin',
    zip_code: '10250',
    lang: 'en',
  },
  {
    store_code: 'robinson_srinakarin_th',
    store_name: 'Robinson Srinakarin',
    zip_code: '10250',
    lang: 'th',
  },
  {
    store_code: 'all_seasons_en',
    store_name: 'All Seasons',
    zip_code: '10330',
    lang: 'en',
  },
  {
    store_code: 'all_seasons_th',
    store_name: 'All Seasons',
    zip_code: '10330',
    lang: 'th',
  },
  {
    store_code: 'esplanade_en',
    store_name: 'Esplanade',
    zip_code: '10440',
    lang: 'en',
  },
  {
    store_code: 'esplanade_th',
    store_name: 'Esplanade',
    zip_code: '10440',
    lang: 'th',
  },
  {
    store_code: 'mbk_en',
    store_name: 'MBK',
    zip_code: '10330',
    lang: 'en',
  },
  {
    store_code: 'mbk_th',
    store_name: 'MBK',
    zip_code: '10330',
    lang: 'th',
  },
  {
    store_code: 'nang_linchee_en',
    store_name: 'Nang Linchee',
    zip_code: '10120',
    lang: 'en',
  },
  {
    store_code: 'nang_linchee_th',
    store_name: 'Nang Linchee',
    zip_code: '10120',
    lang: 'th',
  },
  {
    store_code: 'piyarom_en',
    store_name: 'Piyarom',
    zip_code: '10260',
    lang: 'en',
  },
  {
    store_code: 'piyarom_th',
    store_name: 'Piyarom',
    zip_code: '10260',
    lang: 'th',
  },
  {
    store_code: 'sukhapibal_en',
    store_name: 'Sukhapibal 3',
    zip_code: '10240',
    lang: 'en',
  },
  {
    store_code: 'sukhapibal_th',
    store_name: 'Sukhapibal 3',
    zip_code: '10240',
    lang: 'th',
  },
  {
    store_code: 'sukhumvit_41_en',
    store_name: 'Sukhumvit 41',
    zip_code: '10110',
    lang: 'en',
  },
  {
    store_code: 'sukhumvit_41_th',
    store_name: 'Sukhumvit 41',
    zip_code: '10110',
    lang: 'th',
  },
  {
    store_code: 'thonglor_en',
    store_name: 'Thonglor',
    zip_code: '10110',
    lang: 'en',
  },
  {
    store_code: 'thonglor_th',
    store_name: 'Thonglor',
    zip_code: '10110',
    lang: 'th',
  },
  {
    store_code: 'silom_en',
    store_name: 'Silom',
    zip_code: '10500',
    lang: 'en',
  },
  {
    store_code: 'silom_th',
    store_name: 'Silom',
    zip_code: '10500',
    lang: 'th',
  },
  {
    store_code: 'udomsuk_en',
    store_name: 'Udomsuk',
    zip_code: '10250',
    lang: 'en',
  },
  {
    store_code: 'udomsuk_th',
    store_name: 'Udomsuk',
    zip_code: '10250',
    lang: 'th',
  },
  {
    store_code: 'amorini_en',
    store_name: 'Amorini',
    zip_code: '10230',
    lang: 'en',
  },
  {
    store_code: 'amorini_th',
    store_name: 'Amorini',
    zip_code: '10230',
    lang: 'th',
  },
  {
    store_code: 'silom_complex_en',
    store_name: 'Silom Complex',
    zip_code: '10500',
    lang: 'en',
  },
  {
    store_code: 'silom_complex_th',
    store_name: 'Silom Complex',
    zip_code: '10500',
    lang: 'th',
  },
  {
    store_code: 'kaset_en',
    store_name: 'Kaset',
    zip_code: '10900',
    lang: 'en',
  },
  {
    store_code: 'kaset_th',
    store_name: 'Kaset',
    zip_code: '10900',
    lang: 'th',
  },
  {
    store_code: 'thanya_park_en',
    store_name: 'Thanya Park',
    zip_code: '10250',
    lang: 'en',
  },
  {
    store_code: 'thanya_park_th',
    store_name: 'Thanya Park',
    zip_code: '10250',
    lang: 'th',
  },
  {
    store_code: 'century_plaza_en',
    store_name: 'Century Plaza',
    zip_code: '10400',
    lang: 'en',
  },
  {
    store_code: 'century_plaza_th',
    store_name: 'Century Plaza',
    zip_code: '10400',
    lang: 'th',
  },
  {
    store_code: 'plearnary_en',
    store_name: 'Plearnary',
    zip_code: '10220',
    lang: 'en',
  },
  {
    store_code: 'plearnary_th',
    store_name: 'Plearnary',
    zip_code: '10220',
    lang: 'th',
  },
  {
    store_code: 'the_jas_wanghin_en',
    store_name: 'The Jas Wanghin',
    zip_code: '10230',
    lang: 'en',
  },
  {
    store_code: 'the_jas_wanghin_th',
    store_name: 'The Jas Wanghin',
    zip_code: '10230',
    lang: 'th',
  },
  {
    store_code: 'prannok_en',
    store_name: 'Prannok',
    zip_code: '10700',
    lang: 'en',
  },
  {
    store_code: 'prannok_th',
    store_name: 'Prannok',
    zip_code: '10700',
    lang: 'th',
  },
  {
    store_code: 'taling_chan_en',
    store_name: 'Taling Chan',
    zip_code: '10170',
    lang: 'en',
  },
  {
    store_code: 'taling_chan_th',
    store_name: 'Taling Chan',
    zip_code: '10170',
    lang: 'th',
  },
  {
    store_code: 'supreme_complex_en',
    store_name: 'Supreme Complex',
    zip_code: '10300',
    lang: 'en',
  },
  {
    store_code: 'supreme_complex_th',
    store_name: 'Supreme Complex',
    zip_code: '10300',
    lang: 'th',
  },
  {
    store_code: 'buddhamonthon_en',
    store_name: 'Buddhamonthon',
    zip_code: '10170',
    lang: 'en',
  },
  {
    store_code: 'buddhamonthon_th',
    store_name: 'Buddhamonthon',
    zip_code: '10170',
    lang: 'th',
  },
  {
    store_code: 'prachanivet_en',
    store_name: 'Prachanivet',
    zip_code: '10900',
    lang: 'en',
  },
  {
    store_code: 'prachanivet_th',
    store_name: 'Prachanivet',
    zip_code: '10900',
    lang: 'th',
  },
  {
    store_code: 'rca_en',
    store_name: 'RCA',
    zip_code: '10310',
    lang: 'en',
  },
  {
    store_code: 'rca_th',
    store_name: 'RCA',
    zip_code: '10310',
    lang: 'th',
  },
  {
    store_code: 'ladya_en',
    store_name: 'Ladya',
    zip_code: '10600',
    lang: 'en',
  },
  {
    store_code: 'ladya_th',
    store_name: 'Ladya',
    zip_code: '10600',
    lang: 'th',
  },
  {
    store_code: 'the_explace_en',
    store_name: 'The Explace',
    zip_code: '10160',
    lang: 'en',
  },
  {
    store_code: 'the_explace_th',
    store_name: 'The Explace',
    zip_code: '10160',
    lang: 'th',
  },
  {
    store_code: 'i_place_ladkrabang_en',
    store_name: 'i-Place Ladkrabang',
    zip_code: '10520',
    lang: 'en',
  },
  {
    store_code: 'i_place_ladkrabang_th',
    store_name: 'i-Place Ladkrabang',
    zip_code: '10520',
    lang: 'th',
  },
];

const get = zipCode => find(
  mockStores,
  _store => _store.zip_code === zipCode,
);

const getAll = () => (
  mockStores
);
export default {
  get,
  getAll,
};
