export const creditCardEventType = {
  CC_SUBMIT_FORM: 'CC_SUBMIT_FORM',
  CC_SUBMIT_FORM_RESPONSE: 'CC_SUBMIT_FORM_RESPONSE',
  CC_BIN_LOOKUP: 'CC_BIN_LOOKUP',
  CC_HANDLE_CHANGE: 'CC_HANDLE_CHANGE',
  CC_HEIGHT_CHANGE: 'CC_HEIGHT_CHANGE',
};
